export {default as Hero} from './Hero/Hero'
export {default as Advantage} from './Advantage/Advantage'
export {default as Description} from './Description/Description'
export {default as Transition} from './Transition/Transition'
export {default as Footer} from './Footers/Footers'
export {default as Registration} from './Registration/Registration'
export {default as Organisation} from './Organisation/Organisation'